name: GitHub Actions Demo
run-name: Basic tests 🚀
on: [push]
jobs:
  Norm-and-compile:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install pip norminette
        run: |
          sudo apt-get update && sudo apt-get install -y python3-pip make clang libghc-readline-dev
          pip3 install norminette
      - name: Norminette start
        continue-on-error: true
        run: |
          norminette -R CheckForbiddenSourceHeader | grep -v OK && exit 1
      - name: Try to compile
        run: |
          make || exit 1